### PR TITLE
Rebase GLib to 2.61.3 (Debian)

### PR DESCRIPTION
**Pull request by pwithnall**
This is for review only and **should not be merged**. I’ll push the branches directly when it’s approved.

Code changes here: https://github.com/endlessm/glib/pull/63

https://phabricator.endlessm.com/T27550

### CODE REVIEW

**Review by andrunko — APPROVED** [review]
lgtm once source changes are integrated.

**Comment by pwithnall** [comment]
Updated to be a 2.61.3 release, rather than 2.61.2.

**Review by andrunko — APPROVED** [review]
Still good to me.

**Comment by pwithnall** [comment]
Thanks for the review. [Merged manually](https://phabricator.endlessm.com/T27550#749594).

**Pull request merged**
