### PR TITLE
Rebase on GLib 2.59.3

### PR DESCRIPTION
**Pull request by pwithnall**
https://phabricator.endlessm.com/T25384

This is a bit of a new approach to packaging; the `debian-master` branch will be deleted when this is merged. I have based this package of GLib on the [Debian git repository](https://salsa.debian.org/gnome-team/glib), which is based on the upstream release, with additional commits on top to add the `debian/` directory. This means that:
 * Keeping in sync with Debian is easier (which is what we should be aspiring to)
 * Since `debian/patches/` is disabled, the source code viewable in github is what we’re compiling
 * Future changes to our fork of GLib can be made in a single PR, rather than one for `master` and one for `debian-master`
 * We do disable `debian/patches/`, which makes us differ from Debian upstream

This gives us the GLib 2.59.3 release. (Edit: I originally based on the 2.59.2 release, with some cherry-picked fixes on top; `debian/experimental` has since moved to 2.59.3 (including those patches) and I have rebased on that instead.) We should rebase again once GLib 2.60.0 is released in mid-March, but there will be very few differences.

Relevant diffs, which will be helpful when reviewing, and which look reasonable to me:
 * [`git diff new-master..debian-master -- debian/`](https://gist.github.com/pwithnall/f3deaa0843e5802ada8852660757ff84)
 * [`git diff new-master..upstream/2.59.2 !(debian)`](https://gist.github.com/pwithnall/2e7b40c39333f4874a14b8901aec0ae1)

Rebase plan (`git rebase -i salsa/debian/experimental`), listing what I’ve done with each of the commits. After doing what’s below, I reordered the commits to be in the same order as `debian/patches/series`, then added some packaging fixes. Note: this rebase plan is from when I rebased on `debian/experimental`’s 2.59.2 release; I have since rebased on 2.59.3, but there are no noteworthy changes.

pick ad05f47fc Call gettext a .desktop file does not have inline translations
 • **keep**: still in `debian/patches/series`
pick 53d1c046c Support X-{Debian,Ubuntu}-Gettext-Domain for .desktop files
 • **keep**: still in `debian/patches/series`
pick 5f16181f9 Disable confusing (to users) warning about deprecated schema paths
 • **keep**: still in `debian/patches/series`
pick 4d024c788 Handle the G_HOME environment variable to override the passwd entry
 • **keep**: reapplied `debian/04_homedir_env.patch` from `debian/patches`
pick 5ebc8f2f9 Do not fail the /thread/thread4 test if prctrl() fails
 • **keep**: reapplied `debian/06_thread_test_ignore_prctl_fail.patch` from `debian/patches`
pick 0da102fad Disable tests on slow architectures which keep failing the tests
 • **keep**: reapplied `debian/Disable-some-tests-on-slow-architectures-which-keep-faili.patch` from `debian/patches`
pick 93ec4ec25 Adjust path to glib-compile-schemas in the pkg-config file
 • **keep**: reapplied `debian/61_glib-compile-binaries-path.patch` from `debian/patches`
pick 1f25a2ec0 gio: add fallback directory for pre-multiarch compatibility
 • **keep**: still in `debian/patches/series`
pick 96085df1f Skip the monitor test on non-linux as it currently hangs
 • **keep**: still in `debian/patches/series`
pick b38ef8f77 timer test: use 'volatile' for locals
 • **keep**: still in `debian/patches/series`
pick b79f57775 Skip test which performs some unreliable floating point comparisons
 • **keep**: still in `debian/patches/series`
pick 6c10a7813 Fix trashing on overlayfs
 • **dropped**: different fix for 2.60 as 2.58 (upstream has 1152d99dedd8f5105c81745d8a91fa660de736c9)
pick 280b6c2f2 tests: disable some more slow tests on ARM
 • **dropped**: we now have a faster ARM builder; there have been some Debian packaging changes to mark slow ARM tests as such
pick 44a8a9888 gutils: add API to get user special directory for desktop ID
 • **dropped**: T25445
pick ce60efe97 tests: Handle root changing to non-executable directories
 • **dropped**: fixed independently upstream as c8cbfd551c
pick f06234afa tests: keyfile writability not affected by file mode for root
 • upstreamed as two commits: https://gitlab.gnome.org/GNOME/glib/merge_requests/672
 • **kept** our old downstream version, which can be dropped when we rebase to 2.60 proper
pick 5a32c98ea Makefile: Move to AM_DISTCHECK_CONFIGURE_FLAGS
 • **dropped**: upstream has dropped autotools
pick b6cf1e0b8 gmessages: Fix -Wformat warnings for g_message() and friends
 • **dropped**: trivially different from upstream (32cc60dbff)
pick 9558f6e73 docs: Mention that we build with strict-aliasing disabled
 • **dropped**: trivially different from upstream (e42ff0105d19)
pick f17b6b24d gunixmounts: Allow root to display mounts under /run/media/$username
 • **dropped**: trivially different from upstream (c672fcc0a8d677e93e27cede5270185c0886ea3b)
pick d664805ab GDateTime: Support parsing ISO 8601 strings
 • **dropped**: substantially but irrelevantly different from upstream (491f835c17d200ede52c823ab1566c493479cdc1)
pick 345c51c72 gmain: add g_clear_handle_id API
 • **dropped**: trivially different from upstream (5ebd8f6e88734c2a1c8574ff4af681a2eb9c74a5)
pick e27abc849 gdatetime: Add g_date_time_get_timezone() accessor
 • **dropped**: trivially different from upstream (9ddd17d304642cd42f5e6a76af5cdadb46399ad0)
pick 4dee03cde gtimezone: Add g_time_zone_get_identifier() accessor
 • **dropped**: substantially but irrelevantly different from upstream (8945227743a26a4fe6966baaf082dd6516e8a03c)
pick d4c2a4920 gtype: improve get_type fast path
 • **dropped**: substantially but irrelevantly different from upstream (e924f777369710221c3e0a9d7bf40392a27d1fa4)
pick 3e8328fff fileutils: Add g_canonicalize_filename
 • **dropped**: substantially but irrelevantly different from upstream (b9b642de06e714584e89aa7b8d878a98599538ed)
pick bc8b41c9f gspawn: Add g_spawn_async_with_fds variant
 • **dropped**: substantially but irrelevantly different from upstream (3524de16e46350573536c610d776611d9834b554)
pick db64411bc gspawn: Optimize with posix_spawn codepath
 • **dropped**: substantially but irrelevantly different from upstream (61f54591acdfe69315cef6d1aa6d3bf1ff763082)
pick 00698d721 gdesktopappinfo: enable fast posix_spawn gspawn codepath
 • **dropped**: substantially but irrelevantly different from upstream (742efe6232aba81c2c52c229c900a57ec2afedfd)
pick b38f0eb3c gdesktopappinfo: add g_desktop_app_info_launch_uris_as_manager_with_fds variant
 • **dropped**: trivially different from upstream (156d009696e9873b9298774a11537966da15a26b)
pick 7bed7ea77 Add missing introspection annotations to gvdb_table_get_names()
 • **kept**: applied without changes; ready to drop when we next rebase as it’s been merged upstream as https://gitlab.gnome.org/GNOME/glib/merge_requests/674
pick a44329c24 Fix type of length returned by gvdb_table_get_names()
 • **kept**: applied without changes; ready to drop when we next rebase as it’s been merged upstream as https://gitlab.gnome.org/GNOME/glib/merge_requests/674
pick 084e1d868 Preallocate a GPtrArray to avoid some reallocations later on
 • **kept**: applied without changes; ready to drop when we next rebase as it’s been merged upstream as https://gitlab.gnome.org/GNOME/glib/merge_requests/674
pick 0f4807fbe gresource: Port to new GVDB API
 • **dropped**: trivially different from upstream (705dd2b9a9d4bdbd4b5a59dc7a4d64755b956033)
pick 3edbd24d4 gsettingsschema: Port to new GVDB API
 • **dropped**: trivially different from upstream (c652d45c97f18ab4976b975766fe6d65e7cf3d94)
pick a8c51566f GResource – Create an internal copy of the GBytes if it is not pointer aligned
 • **dropped**: trivially different from upstream (7b60708204354da877f7eda5150631223bba42f2)
pick 23fef9f45 gvdb: Fix error handling in gvdb_table_new()
 • **dropped**: trivially different from upstream (614adf8a7503913de10203c05a41434d6051c0c7)
pick 4c2f6e565 gvarianttype: Impose a recursion limit of 128 on variant types
 • **dropped**: trivially different from upstream (7c4e6e9fbe473de0401c778c6b0c4aad27d5145a)
pick cec44fcdd gutf8: Add a g_utf8_validate_len() function
 • **dropped**: trivially different from upstream (7a4025cac1d0d29b086e30a7d5f7a98ffe3e9df5); different versions were applied to different branches for API stability reasons
pick 74920e24e glib: Port various callers to use g_utf8_validate_len()
 • **dropped**: trivially different from upstream (1c421b0158abb5634e0a38c02860f396f2063e1b)
pick b57507f45 gvariant: Realign data on construction if it’s not properly aligned
 • **dropped**: trivially different from upstream (0f2a6c61c9c5e34d57293fb6987b21f3d1feb1cb)

### CODE REVIEW

**Comment by pwithnall** [comment]
If this passes review, **please do not merge it**. I need to force-push it over `master`, and delete the `debian-master` branch.

**Comment by pwithnall** [comment]
bot, retest this please

**Comment by pwithnall** [comment]
bot, retest this please

**Comment by wjt** [comment]
retest this please, o wise robot

**Comment by wjt** [comment]
retest this please, now that I have *actually* deployed the Jenkins changes from https://github.com/endlessm/eos-build/pull/905

**Comment by pwithnall** [comment]
retest this please, because I worry about the `gsocketclient-slow` test

**Comment by pwithnall** [comment]
> retest this please, because I worry about the `gsocketclient-slow` test

It’s an upstream bug: https://gitlab.gnome.org/GNOME/glib/issues/1693 :weary:

**Comment by pwithnall** [comment]
retest this please, now that I have pushed a `Version_2.59.3` tag

**Comment by pwithnall** [comment]
retest this please

**Comment by pwithnall** [comment]
retest this please

**Comment by pwithnall** [comment]
woohoo, tests passed. I had to push a temporary commit to the `debian-new-master` branch so its tag wasn’t picked up as the tag for the code branch. That’s a tooling wart which should go away when the `debian-master` branch is deleted, I think. Otherwise it might need a trivial fix. In any case, it’s an artifact of this approach to rebasing the branch, rather than a problem with the new version of GLib.

**Comment by GeorgesStavracas** [comment]
And since https://gitlab.gnome.org/GNOME/glib/merge_requests/674 was merged, I guess a few more patches can be dropped too.

**Comment by pwithnall** [comment]
Abandoning this in favour of #54 and #55, as per https://phabricator.endlessm.com/T25384#682620.

**Pull request closed without merging**
