### PR TITLE
Rebase GLib to 2.61.3

### PR DESCRIPTION
**Pull request by pwithnall**
This is for review only **and should not be merged**. I’ll push the branches directly when it’s approved.

Debian changes here: https://github.com/endlessm/glib/pull/64

https://phabricator.endlessm.com/T27550

### CODE REVIEW

**Comment by pwithnall** [comment]
[One of the tests is failing on Jenkins](https://ci.endlessm-sf.com/job/obs-glib-pr/51/console). I’ll look at it next week.

**Comment by andrunko** [comment]
hmm, as is this PR is kinda impossible to review. Could we do something like:
- Create a branch matching upstream glib 2.61.2
- Add our patches on top in a separate branch
- Create a PR with only the diffs from the endless branch and the upstream branch
- Add comments to the PR for patches dropped (e.g. patches already included upstream)
- And any other comment that may be relevant

Yes, that would require force pushing our changes once done, but I think it would be better/easier to review.

What do you think?

**Comment by pwithnall** [comment]
I’ve just updated this to sit on top of the upstream 2.61.3 release and fixed the Jenkins test failure. All you need to review are the commits above the upstream `2.61.3` release itself.

Here’s some diffs of:
 * [`git diff 2.60.1..origin/master`](https://phabricator.endlessm.com/P673) (our difference from upstream before rebasing)
 * [`git diff 2.61.3..T27550-rebase`](https://phabricator.endlessm.com/P674) (our difference from usptream after rebasing)

And here’s what happened to all the commits we used to have on top of upstream before the rebase:
 * 53a4e56c3 Call gettext a .desktop file does not have inline translations
   * Kept
 * 9deb29674 Skip the monitor test on non-linux as it currently hangs
   * Dropped: upstream in 5299e8754ceef8f25044fceb4506e3382a055658
 * 393455c19 timer test: use 'volatile' for locals
   * Kept
 * 565628ceb gwakeuptest: Be less parallel unless invoked with -m slow
   * Kept
 * af257d6d5 Support X-{Debian,Ubuntu}-Gettext-Domain for .desktop files
   * Kept
 * 258f15d4d Disable confusing (to users) warning about deprecated schema paths
   * Kept
 * 0413743d0 Handle the G_HOME environment variable
   * Dropped in Debian in https://salsa.debian.org/gnome-team/glib/merge_requests/3
 * f59510e36 Do not fail the /thread/thread4 test if prctrl() fails
   * Kept; updated with changes in Debian
 * 66b8f798a Adjust path to glib-compile-schemas in the pkg-config file
   * Kept; updated with changes in Debian
 * 3ec1654ea gio: add fallback directory for pre-multiarch compatibility
   * Dropped in Debian
 * 1b91eeee4 Look for gio-launch-desktop in $(libdir)/glib-2.0
   * Kept
 * 8442d45e4 closures test: Skip on arm* unless flaky tests are allowed
   * Kept
 * 1fec2fb6d Disable some tests on slow architectures which keep failing the tests
   * Kept
 * 16c4cdbd9 Skip test which performs some unreliable floating point comparisons
   * Kept
 * 42d7843dd Skip unreliable test_threaded_singleton() by default
   * Kept

And the following new commits have appeared:
 * d07103db6 gmenumodel test: Mark as flaky
   * New in Debian
 * 772619201 gvariant test: Don't run at build-time on mips
   * New in Debian
 * 4239dda38 Disable an optimization when building with gcc 9
   * New in Debian
 * 56ea7e81e tests: Fix skipping mkdir-with-parents-permission test
   * Fixes the Jenkins failure; submitted upstream as https://gitlab.gnome.org/GNOME/glib/merge_requests/1080

**Review by andrunko — APPROVED** [review]
@pwithnall Thanks, changes lgtm, not merging as per request.

**Comment by pwithnall** [comment]
Thanks for the review. [Merged manually](https://phabricator.endlessm.com/T27550#749594).

**Pull request merged**
