### PR TITLE
T29304 Rebase to GLib 2.64.0

### PR DESCRIPTION
**Pull request by pwithnall**
Rebased on `2.64.0` tag from upstream and refreshed the patches from the updated Debian packaging. No other changes; all fairly trivial.

Debian packaging changes in #77.

**This should not be merged using the web UI; it needs to be pushed from the CLI.**

https://phabricator.endlessm.com/T29304

### CODE REVIEW

**Comment by pwithnall** [comment]
(Fairly arbitrarily chosen reviewers; please reassign if you don’t have time to review this!)

**Comment by wjt** [comment]
At what point should we move this over to OBS?

**Comment by pwithnall** [comment]
> At what point should we move this over to OBS?

Will and I discussed this today, and the answer is “for 2.64.1” — see [T29478](https://phabricator.endlessm.com/T29478).

**Comment by pwithnall** [comment]
Change of plan: smcv has pushed 2.64.0 to Debian experimental, but it has some non-trivial changes from the version I grabbed for this PR, so it’s going to be just as easy to move GLib to OBS as it will be to update the PR.

Closed in favour of https://phabricator.endlessm.com/T29478.

**Pull request closed without merging**
